services:
    anavaro.birthdaycontrol.acplistener:
        class: anavaro\birthdaycontrol\event\acplistener
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
        tags:
            - { name: event.listener }